## Laboratory 8 : System of Linear Equations

In [1]:
import numpy as np
import matplotlib.pyplot as plt
%matplotlib inline

##Exercise 1 

In [3]:
A = np.array([
    [1,2,3],
    [6,1,4],
    [3,3,1]
])

B = np.array([
    [10],
    [4],
    [8]
])

print("Matrix x: \n", A)
print("\nMatrix y: \n", B)


A_inv = np.linalg.inv(A)
print("\nResult: ")
print(A_inv @ B)

Matrix x: 
 [[1 2 3]
 [6 1 4]
 [3 3 1]]

Matrix y: 
 [[10]
 [ 4]
 [ 8]]

Result: 
[[-0.91304348]
 [ 3.04347826]
 [ 1.60869565]]


##Exercise 2

In [4]:
A_inv1 = np.linalg.solve(A, B)

print("Matrix x: \n", A)
print("\nMatrix y: \n", B)

print("\nResult: ")
print(A_inv1)

Matrix x: 
 [[1 2 3]
 [6 1 4]
 [3 3 1]]

Matrix y: 
 [[10]
 [ 4]
 [ 8]]

Result: 
[[-0.91304348]
 [ 3.04347826]
 [ 1.60869565]]
