#**Laboratory 6: Matrices**




### Task 1



In [33]:
import numpy as np
import matplotlib.pyplot as plt
%matplotlib inline

In [26]:
def mat_desc(x):
    print(x)
    if x.size > 0:
        is_square = True if x.shape[0] == x.shape[1] else False 
        print("Shape/Size: ", x.shape)
        print("Rank: ", x.ndim)
        print("Is an Square Matrix: ", is_square)
        is_zeros = not np.any(x)
        print("Is an Zero Matrix: ", is_zeros)
        is_ones = np.all((x == 1))
        print("Is an Ones Matrix: ", is_ones)
        #initialization of the length of rows and columns
        rows = len(x);  
        cols = len(x[0]);  
        is_identity=True
        #checking whether the diagonal is 1 and remaining values are 0 
        for i in range(0, rows):  
                for j in range(0, cols):  
                    if(i == j and x[i][j] != 1):  
                        is_identity = False
                    if(i != j and x[i][j] != 0):  
                        is_identity = False
        if is_identity:
            print("Is an Identity Matrix")
        else:
            print("Is not an Identity Matrix")

In [36]:
A = np.array([[2,2,1],[1,2,3],[3,3,5]])
B = np.array([[1,0,0],[5,4,1],[0,0,0]])
C = np.array([[4,2,3],[5,1,2],[6,1,1]])
D = np.array([[5,1,2],[1,1,2],[8,2,1]])
E = np.array([[5,5,3],[3,3,2],[1,1,1]]) ## Matrix declarations

In [28]:
mat_desc(A)

[[2 2 1]
 [1 2 3]
 [3 3 5]]
Shape/Size:  (3, 3)
Rank:  2
Is an Square Matrix:  True
Is an Zero Matrix:  False
Is an Ones Matrix:  False
Is not an Identity Matrix


In [29]:
mat_desc(B)

[[1 0 0]
 [5 4 1]
 [0 0 0]]
Shape/Size:  (3, 3)
Rank:  2
Is an Square Matrix:  True
Is an Zero Matrix:  False
Is an Ones Matrix:  False
Is not an Identity Matrix


In [30]:
mat_desc(C)

[[4 2 3]
 [5 1 2]
 [6 1 1]]
Shape/Size:  (3, 3)
Rank:  2
Is an Square Matrix:  True
Is an Zero Matrix:  False
Is an Ones Matrix:  False
Is not an Identity Matrix


In [31]:
mat_desc(D)

[[5 1 2]
 [1 1 2]
 [8 2 1]]
Shape/Size:  (3, 3)
Rank:  2
Is an Square Matrix:  True
Is an Zero Matrix:  False
Is an Ones Matrix:  False
Is not an Identity Matrix


In [32]:
mat_desc(E)

[[5 5 3]
 [3 3 2]
 [1 1 1]]
Shape/Size:  (3, 3)
Rank:  2
Is an Square Matrix:  True
Is an Zero Matrix:  False
Is an Ones Matrix:  False
Is not an Identity Matrix




### Task 2




In [48]:
def mat_operations(x,y):
    print("Array 1: \n", x)
    print("\nArray 2: \n", y)
    print("\nIs Scalar(Array1): ",isinstance(x, (int, float, complex, bytes)))
    print("\nIs Scalar(Array2): ",isinstance(y, (int, float, complex, bytes)))
    check_scalar1 = isinstance(x, (int, float, complex, bytes))
    check_scalar2 = isinstance(y, (int, float, complex, bytes))
    check_array1 = isinstance(x, np.ndarray)
    check_array2 = isinstance(y, np.ndarray)
    if check_scalar1 == True or check_scalar2 == True or check_array1 == True and check_array2 == True and x.shape == y.shape:
        print("\nSum of the two arrays: ")
        print(x+y)
        print("\nDifference of two arrays: ")
        print(x-y)
        print("\nProduct of the two arrays: ")
        print(x*y)
        print("\nQuotient of the two arrays: ")
        print(x/y)
    elif check_array1 == True and check_array2 == True and x.shape != y.shape:
        print("\nCan't perform certain operations, Shapes of array should be equal.")

In [49]:
F = np.array([[2,1,2],[5,4,1],[5,1,2]])
G = np.array([[1,1,2],[3,1,1],[1,8,4]])
H = np.array([[1,9,1],[1,3,2],[1,2,5]])
I = np.array([[9,8,7],[7,5,6],[8,3,2],[2,4,6]])
J = np.array([[5,1,1],[3,2,1],[2,6,8]])

In [52]:
print("matrices pair 1:\n")
mat_operations(F,G)
print("matrices pair 2:\n")
mat_operations(H,I)
print("matrices pair 3:\n")
mat_operations(J,F)


matrices pair 1:

Array 1: 
 [[2 1 2]
 [5 4 1]
 [5 1 2]]

Array 2: 
 [[1 1 2]
 [3 1 1]
 [1 8 4]]

Is Scalar(Array1):  False

Is Scalar(Array2):  False

Sum of the two arrays: 
[[3 2 4]
 [8 5 2]
 [6 9 6]]

Difference of two arrays: 
[[ 1  0  0]
 [ 2  3  0]
 [ 4 -7 -2]]

Product of the two arrays: 
[[ 2  1  4]
 [15  4  1]
 [ 5  8  8]]

Quotient of the two arrays: 
[[2.         1.         1.        ]
 [1.66666667 4.         1.        ]
 [5.         0.125      0.5       ]]
matrices pair 2:

Array 1: 
 [[1 9 1]
 [1 3 2]
 [1 2 5]]

Array 2: 
 [[9 8 7]
 [7 5 6]
 [8 3 2]
 [2 4 6]]

Is Scalar(Array1):  False

Is Scalar(Array2):  False

Can't perform certain operations, Shapes of array should be equal.
matrices pair 3:

Array 1: 
 [[5 1 1]
 [3 2 1]
 [2 6 8]]

Array 2: 
 [[2 1 2]
 [5 4 1]
 [5 1 2]]

Is Scalar(Array1):  False

Is Scalar(Array2):  False

Sum of the two arrays: 
[[ 7  2  3]
 [ 8  6  2]
 [ 7  7 10]]

Difference of two arrays: 
[[ 3  0 -1]
 [-2 -2  0]
 [-3  5  6]]

Product of the two 